### ISSUE TITLE
Add new student Individual Supporter product

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#434] opened 2015-06-22 10:18 UTC
As an undergraduate starting a computer science course I want to take up the offer of free individual Supporter membership at the ODI. I receive an email from my head of department explaining the ODI free membership offer. Once I decide to go ahead with membership I want to click on a link within the email which asks me for my customer information (and does not take long to complete). I do not want to have to enter my credit card details in order to register as an individual Supporter. I then want to receive an automated welcome email which explains my student membership to me and asks me to login to my account. 

As a membership manager I need a new ‘student’ tier membership to be added into the individual Supporter registration page when accessed by a specific link (but hidden from ordinary users). This has been created in Chargify already (with API handle: individual-supporter-student) but needs to be picked up by the member directory. 
NB
Can you check the return parameters within Chargify are correct (I copied from other products but I don't know if I need to remove the payment ID from the code)?

As a membership manager I would need to have this student tagged as an individual Supporter but also as a student within my CRM system so I can send targeted mailouts to students amongst the member network. 

* [x] Create signup link for student signups (`?level=student`)
* [x] Skip credit card details for "student" level membership
* [x] Customise the signup welcome email for students (based on `#product_name`)
* [x] Student product is `individual-supporter-student`
* [x] Check return parameters within Chargify
* [x] Student members should be tagged in Capsule as "individual       supporter" and "student"
* [x] Change text on the payment page for students

**Comment by jordelver** [comment] 2015-08-13 08:43
> I then want to receive an automated welcome email which explains my student membership to me and asks me to login to my account.

Can you supply the content for the student email, please? Thanks.

**Comment by jordelver** [comment] 2015-08-13 09:05
Take existing email and customise as "Dear Student" for now until we have the correct text

**Comment by jordelver** [comment] 2015-08-17 16:54
This is 99% done. But, what should the payment page text be @georgiap?

![2015-08-17 at 17 52](https://cloud.githubusercontent.com/assets/6588/9310643/ea8e828e-4508-11e5-82b8-c6f10417a1f1.png)

**Comment by georgiap** [comment] 2015-08-17 16:59
Hi Jordan,

How about keeping it simple until the membership team have a clearer plan
for the product? "To complete your registration, please continue to the
next page"

Can we change the wording below the box to read "Being an ODI Student
Supporter is FREE!"

Looks great!

Thanks,

Georgia

**Comment by jordelver** [comment] 2015-08-18 08:18
Sounds like a plan, thanks @georgiap :+1:

**Comment by jordelver** [comment] 2015-08-19 09:09
This has now been added and is live @greenreveller 

It's basically a copy of the individual product but free and there are also some changes to the UI as they didn't make sense when the product is free.

The link is https://directory.theodi.org/members/new?level=student

Can you test you test and let me know what you think?

**Comment by greenreveller** [comment] 2015-08-20 10:20
When I get to https://directory.theodi.org/members/AU9367RD/payment I get this returned: 

![image](https://cloud.githubusercontent.com/assets/5023266/9381122/b0cf7514-472c-11e5-8ff3-6158e1591003.png)

Also:
I need to give you updated T&Cs for students (atm it says they owe us a fee of £90 + VAT) - I will sort that today
The right to cancel page link needs to be updated - see #342 #425 - I tried to change this myself but I think @Floppy deleted the branch I had created?

**Comment by jordelver** [comment] 2015-08-20 11:00
Oh no :( I'll try it out and get back to you

**Comment by jordelver** [comment] 2015-08-20 11:14
This is weird. It works for me. Can you let me know what details you entered into the form field, please @greenreveller ?

**Comment by greenreveller** [comment] 2015-08-20 11:24
ah, didn't write them down anywhere - want me to retest?

**Comment by jordelver** [comment] 2015-08-20 11:28
Yes, please. If you wouldn't mind.

**Comment by greenreveller** [comment] 2015-08-20 11:32
ok so same page: https://directory.theodi.org/members/LX8211YN/payment via Firefox

![image](https://cloud.githubusercontent.com/assets/5023266/9382303/7999b856-4737-11e5-99dc-a1ff1071cca5.png)

User data: 
andrea.cox+teststudent1@theodi.org
Andrea Student
3 Key Lane
London
UK	
G8 4RR

**Comment by greenreveller** [comment] 2015-08-20 15:33
Student T&Cs on hold until I find out the latest on the student strategy while I've been away

**Comment by jordelver** [comment] 2015-08-20 15:56
Understood.

I might have to wait to look at this one until the live member directory is fixed :-/

**Comment by greenreveller** [comment] 2015-08-20 16:00
yep - nps

**Comment by jordelver** [comment] 2015-08-21 09:41
@greenreveller the styling issue was fixed by @pikesley so you can now re-test this.

Perhaps somewhat surprisingly, this error looks like it was caused by the same issue which broke the site styling. Can you re-test when you have a sec @greenreveller?

**Comment by greenreveller** [comment] 2015-08-21 13:58
Just tested (using diff name etc) but same error: 
![image](https://cloud.githubusercontent.com/assets/5023266/9409850/172bea48-4815-11e5-9781-e1d6a1cb9009.png)

**Comment by greenreveller** [comment] 2015-08-24 14:17
So I've just got past the confirmation page - YAY - but then I'm sent to Chargify credit card payment page. The charge is £0 but I'm still asked for my credit card details: 
![image](https://cloud.githubusercontent.com/assets/5023266/9442317/36a4f3b4-4a73-11e5-96a5-50eb957294e2.png)

**Comment by jordelver** [comment] 2015-08-24 15:14
Ok, that's good news. I 99% sure that is just a Chargify configuration. I've just changed it. Can you try once more, please?

**Comment by greenreveller** [comment] 2015-08-24 16:05
Hooray!!
![image](https://cloud.githubusercontent.com/assets/5023266/9445113/4b78464c-4a82-11e5-8c9d-d86bf29ffaea.png)
 All working fine :+1:

**Comment by jordelver** [comment] 2015-08-24 17:23
\o/

**Closed** 2015-08-25 09:08 UTC
Labels: capsulecrm, chargify, enhancement, priority: high
