### ISSUE TITLE
Send a welcome email to Individual Supporters 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#315] opened 2014-11-26 14:51 UTC
As a newly registered Individual Supporter I receive a welcome email confirming my successful sign-up. 

The text of this email is here: 
https://docs.google.com/a/theodi.org/document/d/1co2RkMAkMCzVlrAT0i-yxlOIgXCTylcPmvRym95JAI4/edit

NB This is different to the welcome email which we send to SME/Corporate Supporters

NB Is it possible to include a picture (e.g. of a badge) in this welcome email?

**Comment by greenreveller** [comment] 2015-01-02 13:02
Welcome email text is mostly fine save for the last sentence: 

"If you have any questions or suggestions, please do get in touch by emailing mailto:members@theodi.org." 

Please could you add the link to members@theodi.rg and remove the 'mailto:'?

We are also awaiting further amends from lawyers of individ T&Cs which are attached to welcome email. Will update as soon as I have the amends confirmed.

**Comment by Floppy** [comment] 2015-01-06 14:18
Is this done now?

**Comment by pezholio** [comment] 2015-01-06 14:20
First two things are done in https://github.com/theodi/member-directory/pull/336. @greenreveller - have you had the individual T&Cs confirmed?

**Comment by greenreveller** [comment] 2015-01-06 14:29
Not yet - lawyer to confirm on Thursday so I will update then.


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @UKODImembers
<https://twitter.com/UKODImembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by Floppy** [comment] 2015-01-06 14:33
OK, let's not wait for that though, we can do another PR to change them. Agreed?

**Comment by Floppy** [comment] 2015-01-06 14:33
Marking this as done. Individual T&C update will follow.

**Comment by greenreveller** [comment] 2015-01-29 12:09
Hi, there are a few outstanding changes in the welcome email which haven't made it into the final version. 

i. changes in orange in the following doc: https://docs.google.com/a/theodi.org/document/d/1co2RkMAkMCzVlrAT0i-yxlOIgXCTylcPmvRym95JAI4/edit 

ii. We also wanted picture of a Supporter badge integrated into the welcome email. We would like it positioned to the right of the three bullet points. I'm envisaging a two column layout with the bullet points on the left of the email and the picture on the right. The png we would like to use: https://docs.google.com/a/theodi.org/file/d/0B3eBuwLRqgy1SjFZaHFydmZWNWc/edit

NB point ii was in the comments on the doc which you might not have been able to see

**Comment by greenreveller** [comment] 2015-02-03 20:02
Looks good just a few things which need tweaking
a. change 'community' to 'network' in first sentence - highlighted in pink in the doc. 
b. I think the end date in the last para should be 'start date + 355 days' as the renewal date is on the anniversary of their start date. Can oyu make that change? 
c. There's a paragraph space missing between the paras 'Your membership officially runs....' and 'We'll get in touch one month before....''

Thanks!

**Comment by greenreveller** [comment] 2015-02-03 20:02
NB can see supporter badge as attachment but not embedded (but you may well already be aware of this!)

**Comment by pkqk** [comment] 2015-02-04 11:39
@greenreveller I've sent you a test email via the actual delivery service to check how it looks. It looks ok in Gmail and Apple Mail for me.

I didn't realise it BCC'd to members@theodi though so you might have 2 spares in there.

Also I assume you meant 365 days not 355 ;) I've made it actually calculate the date by adding 1 year and then subtracting 1 day as otherwise contracts will be wrong on leap years (such as next year)

**Comment by greenreveller** [comment] 2015-02-04 14:26
@pkqk  haha, yes! 364 days, doh! Good plan on the leap year thing :)

Three more tweaks that we need doing and then I think we're there: 
a. The numbering seems to have gone a bit askew in the terms & conditions attached in the email. Rather than showing 10.1, 10.2 each sub-para is labelled 1, 2. Is it possible to mirror the numbering in the original T&C doc? https://docs.google.com/a/theodi.org/document/d/1G7Jzt61f2f7aEBn51qHzJCwfsuhjZAG4fU7t0yoRHT4/edit
b. Great to see badge embedded in the email but I think it actually looks a bit big - can we use the smaller version of the same logo? https://docs.google.com/a/theodi.org/file/d/0B3eBuwLRqgy1V2ZCWTYzbF9XS00/edit
c. Couple of tweaks in green in the doc (sorry! keep noticing things!)

**Comment by pkqk** [comment] 2015-02-04 15:53
@greenreveller I've sent you an updated sample.

  - [x] image made smaller
  - [x] new copy applied
  - [x] changed `months’` to `months` in T&Cs

There was styling to make the sub-sections be numbered 10.1, 10.2 etc but it looks like gmail is stripping that when you open it from the browser. Try downloading it and opening it? If this isn't good enough then we might have to think about making it as a pdf which is a bit of a chunk of work.

I did also change the styling of the T&Cs a bit
  - [x] changed font to sans serif, will default to Arial or Helvetica on most systems
  - [x] added the borders around the table
  - [x] changed the padding and list indentation a bit to make it more readable

Also if you keep noticing things I can show you how to make small text changes in the github editor.

**Comment by greenreveller** [comment] 2015-02-04 16:16
Thanks for your eagle eye Adam. Yes, would be good to run through the
github editor with you - I used to be able to do edits but I need a bit of
a refresher as and when.

I didn't get a new welcome email sent through though...


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @UKODImembers
<https://twitter.com/UKODImembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by pkqk** [comment] 2015-02-04 16:34
I tried sending again.

**Comment by greenreveller** [comment] 2015-02-04 17:33
still nothing :(


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @UKODImembers
<https://twitter.com/UKODImembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by pkqk** [comment] 2015-02-04 17:57
@greenreveller I cannot type words, try looking again.

**Comment by pkqk** [comment] 2015-02-04 18:06
closed by #354

**Comment by greenreveller** [comment] 2015-02-05 11:53
sorry! one last amend (my bad for not checking properly yst)

one of yesterdays' edit didn't make it over into the email - have highlighted in turquoise (running out of colours now!)

The 'stay ahead of the curve' para should read: 

We’ll be pinging you through the membership e-newsletter every month and you'll also receive priority notification of ODI Summit discounts and selected access to other ODI events.

we're currently missing 'you'll also'

**Comment by pkqk** [comment] 2015-02-05 15:45
@greenreveller might have to do the github tutorial soon :)

I've added the `you’ll also`, but the change to `member network` from `community` was already there, are you looking at the most recent copy I sent?

**Comment by greenreveller** [comment] 2015-02-05 16:55
indeed ;)

there was only the one change in turquoise this time ('member network' was in pink from a previous change)

**Comment by pkqk** [comment] 2015-02-05 17:15
ah, I'll blame this on being slightly colourblind and not just not knowing the names of colours.

**Closed by pkqk** 2015-02-05 17:15 UTC
