### ISSUE TITLE
Directory Admin access

### ISSUE THREAD

**Issue by carlrodriguesodi** [theodi/member-directory#301] opened 2014-09-23 10:32 UTC
Hi, 
I can't access the admin function of the member directory. I used to select Admin and go straight in via my having a Google account, but this stopped working some weeks ago. 
Can you help?
Thanks,  
Carl

**Comment by Floppy** [comment] 2015-01-07 14:32
Closing as dupe of #303

**Closed by Floppy** 2015-01-07 14:32 UTC
