### ISSUE TITLE
100% discounted invoices

### ISSUE THREAD

**Issue by alisonwalters** [theodi/member-directory#374] opened 2015-04-08 14:20 UTC
Hi
We have received an invoice via Chargify / Stripe regarding an individual membership for Joe Pakenham. THis is showing in Xero as £108, but is discounted in Chargify by 100%. Chargify is correct, but it isn't translating correctly to Xero.

thx

**Comment by pkqk** [comment] 2015-04-09 15:01
@alisonwalters as far as I understand it @greenreveller was going to leave invoices on in Stripe until we'd confirmed it was all working and then get @Floppy to disable the Xero invoice creation as it is entirely separate and they're only draft invoices.

Is this correct?

**Comment by greenreveller** [comment] 2015-04-09 15:36
@pkqk That's on hold for now as Louise is talking to auditors about requirements for invoices. 

So we still want invoices on but the issue is that invoice aren't creating properly in Xero (e.g. they are not reflecting the discounts on membership when the invoice is being created. So the revenue figures are being calculated incorrectly in Xero).

**Comment by jordelver** [comment] 2015-08-19 09:02
This is now fixed @greenreveller :smile:  The invoices in Xero are now correct. 

If you could test and close that would be great :+1:

**Comment by greenreveller** [comment] 2015-08-20 12:04
Just tested using coupon MENTOR (which gives 100% discount) but the is showing up without discount applied: 
![image](https://cloud.githubusercontent.com/assets/5023266/9382818/d3d344a0-473b-11e5-9f2a-86925c5ecd08.png)

Individual Supporter 100% discount 20/08
andrea.cox+test100discount@theodi.org
Andrea Discount
3 Key Lane
London
UK
G7 4RR
(then I have used my actual billing address)

**Comment by jordelver** [comment] 2015-08-20 13:04
I think I know what's wrong with this. I'm not sure how it slipped through though :( If you use `&coupon=MENTOR` in the querystring, it works. I'm looking at how to fix now.

**Comment by greenreveller** [comment] 2015-08-20 13:08
ah, I applied the coupon directly on to the chargify page not using the querystring. 

Needs to work in both instances

**Comment by jordelver** [comment] 2015-08-20 15:50
I should have fixed this in https://github.com/theodi/member-directory/pull/467

**Comment by jordelver** [comment] 2015-08-20 17:10
This is ready to be tested again @greenreveller once the styling issues are sorted

**Comment by greenreveller** [comment] 2015-08-24 15:54
Successful test for Individual Supporter using 100% discount code MENTOR:
Correct Payment Page data
Welcome Email generated
Capsule entry created
Invoice correct in Xero
Chargify entry created 

ODI Individual supporter (KU3008MN) [Individual] ( card payment)
![image](https://cloud.githubusercontent.com/assets/5023266/9443035/db908c78-4a76-11e5-9686-e7834a46b9c2.png)

**Comment by greenreveller** [comment] 2015-08-24 15:56
I also tested for SMEs with 100% discount (coupon code: STARTUP using querystring https://directory.theodi.org/members/new?level=supporter&coupon=ODISTARTUP) but when I go through to Chargify payment page the coupon is not being applied. This may be a separate issue entirely?

**Comment by jordelver** [comment] 2015-08-25 08:13
I had a quick look and I can't see why it wouldn't work. This probably is a separate issue.

**Closed** 2015-08-25 09:09 UTC
Labels: bug, chargify, priority: high, xero
