### ISSUE TITLE
Another Supporter can't sign in to Member Directory!

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#358] opened 2015-02-06 12:23 UTC
BT0987SX
ESRI

I am trying to get into our account in order to make some changes in our profile.
 
I could not remember my password so I followed the instructions to get a new one, however , it seems that I am getting in loop to renew my password…   Very frustrating.  I wonder what I do wrong…   Is it the length of the password or composition of it?? Are there rules for it?
 
Thanks,
 
Frank Holsmuller
Esri,  member BT0987SX

**Comment by greenreveller** [comment] 2015-02-06 14:16
@pkqk not sure what the problem is here as he is following the correct link to reset his password and is obviously inputting the same email address as he first used. Any thoughts?

**Comment by pkqk** [comment] 2015-02-10 12:46
duplicate of #357

**Closed by pkqk** 2015-02-10 12:46 UTC
