### ISSUE TITLE
Invoice payments coming up paid in Xero

### ISSUE THREAD

**Issue by Floppy** [theodi/member-directory#450] opened 2015-08-03 13:20 UTC
For people who are paying for membership via invoice we are still getting the invoices displaying in Xero as marked as paid e.g.

ODI Supporter (GS660BY) Non Commercial
PAID BY CREDIT CARD; reference

The 'PAID BY CREDIT CARD; reference' needs to be removed from all invoice payments otherwise Finance team won't know to send the invoices out.

**Comment by jordelver** [comment] 2015-08-12 16:21
If `&level=individual` then the invoice payment method gets set to `credit_card` and the invoice ends up with "PAID WITH CREDIT CARD" added to the invoice.

If `&level=individual&invoice=1` then the invoice payment method gets set to `credit_card` and the invoice ends up with "PAID WITH CREDIT CARD" added to the invoice. So, this is incorrect.

I believe the problem is here:
https://github.com/theodi/member-directory/blob/master/app/models/member.rb#L479

However, if you do `&level=individual&invoice=1` you are still directed to the payment page to pay by credit card. Is that correct? Surely you should not be directed to pay if you have `invoice=1` set?

I think maybe we should leave this ticket until we tackle #445 as we're going to be changing things around anyway and this might become irrelevant.

**Comment by pezholio** [comment] 2015-08-13 08:46
Yup, I think it was a deliberate check. We didn't want individuals to pay by invoice at all initially, although this may have changed now.

**Comment by jordelver** [comment] 2015-08-13 09:11
Thanks @pezholio. I've checked with @georgiap and we're going to bypass the credit card payment credit card screen for individuals if they pay by invoice. This at least makes it consistent.

**Comment by jordelver** [comment] 2015-08-19 09:05
This is now fixed @greenreveller :smile: It's important to note the feedback above ^^^, we decided to skip the payment page if you pay by invoice as that seemed to be how it _should_ work. Can you please do some tests through the whole system to make sure it works as you think it should.

**Comment by greenreveller** [comment] 2015-08-20 10:43
Great stuff. 

I will run tests now for invoice for SME/non-profit and Corporate Supporters. 
NB Credit card payment tests will be tomorrow as I'll need the company credit cards to run 

NB we don't want individuals to have the option to pay by invoice (only orgs - see #413 - appreciate that this isn't very clear in the ticket). This is because it's not worth the Finance team's time tracking down unpaid invoices worth only £108.

**Comment by jordelver** [comment] 2015-08-20 10:58
Thanks @greenreveller 

Yeah, the option to pay by invoice (the link on the payment page) only shows up for non-individuals.

**Closed** 2015-09-24 09:59 UTC
Labels: bug, priority: high, xero
